
package br.com.minaspecas.irmaospereira.agilizapecas.apresentacao;

import static br.com.minaspecas.irmaospereira.agilizapecas.apresentacao.JFrameLoginUsuario.getInstancia;
import br.com.minaspecas.irmaospereira.agilizapecas.entidades.Usuario;
import java.awt.Dimension;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;

/**
 *
 * @author AMAURI PEREIRA
 */
public class JFrameTelaPrincipal extends javax.swing.JFrame {

    // metodo abaixo instancia um Painel de Area de Trabalho(JDP1)
    //O painel JDP1 é area onde os formularios internos vão ser instanciados
    public static JDesktopPane getPainel() {
        return getInstancia().jDesktopPaneTelaPrincipal; 
    }    
    

    //Variavel que recebe os dados do usuario que logou no sistema 
    private static Usuario usuarioLogado; 
    
    /**
     * Creates new form JFrameTelaPrincipal
     */
    public JFrameTelaPrincipal(Usuario userLogado) {
        initComponents();
        this.usuarioLogado = userLogado;
        this.setExtendedState(MAXIMIZED_BOTH);
        this.configBarraStatus();  
                
    }
    
    private void configBarraStatus() {
        this.jLabelUsuarioLogado.setText(usuarioLogado.getUsuario());
    }
    
    public  void getInstanciaCadastroUsuario () {
        
        JInternalFrameCadastroUsuario casdastroUsuario = new JInternalFrameCadastroUsuario();
        casdastroUsuario.setVisible(true);
        centralizaForm(casdastroUsuario);
        casdastroUsuario.toFront();
        jDesktopPaneTelaPrincipal.add(casdastroUsuario);
        
    }
    
    public void getInstanciaCadastroMarca () {
        
        JInternalFrameCadastroMarca casdastroMarca = new JInternalFrameCadastroMarca();
        casdastroMarca.setVisible(true);
        centralizaForm(casdastroMarca);
        casdastroMarca.toFront();
        jDesktopPaneTelaPrincipal.add(casdastroMarca);
        
    }
    
    public void getInstanciaAbrirRequisicao() {
        
        JInternalFrameAbrirRequisicao abrirRequisicao = new JInternalFrameAbrirRequisicao();
        abrirRequisicao.setVisible(true);
        centralizaForm(abrirRequisicao);
        abrirRequisicao.toFront();
        jDesktopPaneTelaPrincipal.add(abrirRequisicao);
        
    }
    
     private void centralizaForm(JInternalFrame frame) {

        Dimension desktopSize = jDesktopPaneTelaPrincipal.getSize();
        Dimension jInternalFrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - jInternalFrameSize.width) / 2, (desktopSize.height - jInternalFrameSize.height) / 2);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelUsuarioLogado = new javax.swing.JLabel();
        jLabelUsuarioLogado1 = new javax.swing.JLabel();
        jLabelUsuario1 = new javax.swing.JLabel();
        jDesktopPaneTelaPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastros = new javax.swing.JMenu();
        jMenuItemUsuario = new javax.swing.JMenuItem();
        jMenuItemMarca = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuConsultas = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuMovimentos = new javax.swing.JMenu();
        jMenuRequisicao = new javax.swing.JMenu();
        jMenuItemAbrir = new javax.swing.JMenuItem();
        jMenuRelatorios = new javax.swing.JMenu();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuParametros = new javax.swing.JMenu();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agiliza Peças - Gerencimento de Requisição");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelUsuario.setText("Usuário:");

        jLabelUsuario1.setText("Setor:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelUsuarioLogado, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelUsuario1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelUsuarioLogado1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1461, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelUsuario1)
                        .addComponent(jLabelUsuarioLogado1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelUsuario)
                        .addComponent(jLabelUsuarioLogado, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jDesktopPaneTelaPrincipalLayout = new javax.swing.GroupLayout(jDesktopPaneTelaPrincipal);
        jDesktopPaneTelaPrincipal.setLayout(jDesktopPaneTelaPrincipalLayout);
        jDesktopPaneTelaPrincipalLayout.setHorizontalGroup(
            jDesktopPaneTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPaneTelaPrincipalLayout.setVerticalGroup(
            jDesktopPaneTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1007, Short.MAX_VALUE)
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jMenuCadastros.setText("Cadastros");

        jMenuItemUsuario.setText("Usuário");
        jMenuItemUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuarioActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemUsuario);

        jMenuItemMarca.setText("Marca");
        jMenuItemMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMarcaActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemMarca);

        jMenuItem3.setText("jMenuItem1");
        jMenuCadastros.add(jMenuItem3);

        jMenuItem4.setText("jMenuItem1");
        jMenuCadastros.add(jMenuItem4);

        jMenuItem5.setText("jMenuItem1");
        jMenuCadastros.add(jMenuItem5);

        jMenuBar1.add(jMenuCadastros);

        jMenuConsultas.setText("Consultas");

        jMenuItem6.setText("jMenuItem1");
        jMenuConsultas.add(jMenuItem6);

        jMenuItem7.setText("jMenuItem1");
        jMenuConsultas.add(jMenuItem7);

        jMenuItem8.setText("jMenuItem1");
        jMenuConsultas.add(jMenuItem8);

        jMenuItem9.setText("jMenuItem1");
        jMenuConsultas.add(jMenuItem9);

        jMenuItem10.setText("jMenuItem1");
        jMenuConsultas.add(jMenuItem10);

        jMenuBar1.add(jMenuConsultas);

        jMenuMovimentos.setText("Movimentos");

        jMenuRequisicao.setText("Requisição");

        jMenuItemAbrir.setText("Abrir");
        jMenuItemAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAbrirActionPerformed(evt);
            }
        });
        jMenuRequisicao.add(jMenuItemAbrir);

        jMenuMovimentos.add(jMenuRequisicao);

        jMenuBar1.add(jMenuMovimentos);

        jMenuRelatorios.setText("Relatórios");

        jMenuItem16.setText("jMenuItem1");
        jMenuRelatorios.add(jMenuItem16);

        jMenuItem17.setText("jMenuItem1");
        jMenuRelatorios.add(jMenuItem17);

        jMenuItem18.setText("jMenuItem1");
        jMenuRelatorios.add(jMenuItem18);

        jMenuItem19.setText("jMenuItem1");
        jMenuRelatorios.add(jMenuItem19);

        jMenuItem20.setText("jMenuItem1");
        jMenuRelatorios.add(jMenuItem20);

        jMenuBar1.add(jMenuRelatorios);

        jMenuParametros.setText("Parâmetros");

        jMenuItem21.setText("jMenuItem1");
        jMenuParametros.add(jMenuItem21);

        jMenuItem22.setText("jMenuItem1");
        jMenuParametros.add(jMenuItem22);

        jMenuItem23.setText("jMenuItem1");
        jMenuParametros.add(jMenuItem23);

        jMenuItem24.setText("jMenuItem1");
        jMenuParametros.add(jMenuItem24);

        jMenuItem25.setText("jMenuItem1");
        jMenuParametros.add(jMenuItem25);

        jMenuBar1.add(jMenuParametros);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jDesktopPaneTelaPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPaneTelaPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuarioActionPerformed
        getInstanciaCadastroUsuario(); 
    }//GEN-LAST:event_jMenuItemUsuarioActionPerformed

    private void jMenuItemMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMarcaActionPerformed
        getInstanciaCadastroMarca();
    }//GEN-LAST:event_jMenuItemMarcaActionPerformed

    private void jMenuItemAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAbrirActionPerformed
        getInstanciaAbrirRequisicao();
    }//GEN-LAST:event_jMenuItemAbrirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameTelaPrincipal(usuarioLogado).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPaneTelaPrincipal;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JLabel jLabelUsuario1;
    private javax.swing.JLabel jLabelUsuarioLogado;
    private javax.swing.JLabel jLabelUsuarioLogado1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastros;
    private javax.swing.JMenu jMenuConsultas;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuItemAbrir;
    private javax.swing.JMenuItem jMenuItemMarca;
    private javax.swing.JMenuItem jMenuItemUsuario;
    private javax.swing.JMenu jMenuMovimentos;
    private javax.swing.JMenu jMenuParametros;
    private javax.swing.JMenu jMenuRelatorios;
    private javax.swing.JMenu jMenuRequisicao;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
